# baseline_new: w3, efficient early fusion, efficient level 3
_BASE_: "../Lite/base_clip_frozen_image_R50.yaml"
FIND_UNUSED_PARAMETERS: False
MODEL:
  WEIGHTS: "weights/converted_maskdino_r50_withoutclip.pth"
  VISUAL_PROMPT: False
  EARLYFUSION: True
  EFFI_EARLY_FUSION: True
  EFFI_LVL: 3
  SEM_SEG_HEAD:
    TRANSFORMER_ENC_LAYERS: 3
  MaskDINO:
    DEC_LAYERS: 3
  LANGUAGE_BACKBONE:
    LANG_DIM: 768
  TEXT:
    ARCH: EVA02_L_CLIP_frozen # frozen
  BACKBONE:
    NAME: D2EfficientViT
  EFFIVIT:
    WIDTH_LIST: [32, 64, 128, 256, 512]
    DEPTH_LIST: [1, 2, 2, 8, 8]
DATASETS:
  TRAIN: ("openimage_train", "objects365_v2_train", )
  TEST: ("objects365_v2_val",)  
SOLVER:  
  IMS_PER_BATCH: 128
  BASE_LR: 0.0001
  STEPS: (240000, ) # [80%]
  WARMUP_ITERS: 1000
  MAX_ITER: 300000
  CHECKPOINT_PERIOD: 10000
  TEXTENCODER_MULTIPLIER: 0.1
TEST:
  EVAL_PERIOD: 0
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [3, 3]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [2, 2]
  USE_RFS: [True, True]
  DATASET_ANN: ['box', 'box']
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
OUTPUT_DIR: ./exp/Final_Stage1_baseline_new_enc3_dec3_evaclipl_64g_L2